### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by hw4m** [L4m4L/simpleBLEJava#1]
The code in the repository doesn't seem to have a license. That effectively means all rights reserved and that using and contributing to the code will be... difficult.

You can checkout [GitHub's licensing help page](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) help you understand how to license your code :-)

Thanks in advance.

**Comment by 4lml4** [comment]
Hi @oizo, thanks for this. Apologies for the very long delay in getting back to you, I have been tied up with a lot of other things off GitHub (unfortunately!)

I have just added a license file - decided that the MIT license was the most appropriate. 

Please let me know if you end up using the code and if you need any help with it. 

Thanks
